### ISSUE TITLE
numericality greaterThan is always required

### ISSUE THREAD

**Issue by droganov** [ansman/validate.js#31] opened 2015-02-12 07:06 UTC
Hello,
I my case price field is optional, but if it's filled, then it should be a positive integer.

How do I configure the schema?

**Comment by ansman** [comment] 2015-02-12 11:09
```javascript
var constraints = {
  price: {
    numericality: {
      onlyInteger: true,
      greaterThan: 0
    }
  }
};

validate({}, constraints);
// => undefined

validate({price: 0}, constraints);
// => {price: ["Price must be greater than 0"]}

validate({price: 1.2}, constraints);
// => {price: ["Price must be an integer"]}
```

**Comment by droganov** [comment] 2015-02-12 11:29
Nicklas, my config is:

```
price:
	numericality:
		greaterThan: 0
		onlyInteger: true
		notGreaterThan: "Положительное число"
```

I see 2 problems.
1. I get `must be greater than 0` exception for an empty field
2. `notGreaterThan` option is replaced with default error message

When I enter positive integer, I see no error message.

Version is 0.4.0

**Comment by ansman** [comment] 2015-02-12 11:33
You cannot set a greater than only message like that. The validators only accepts "message", the other ones are when setting default messages.




I don't really understand problem #1, the validator will accept all integers above 0 and reject all values that aren't empty.

**Comment by droganov** [comment] 2015-02-12 11:36
Ok, I can reconfigure messages, but as for validation,  I expect validator to accept empty value, since the field is not required.

**Comment by ansman** [comment] 2015-02-12 11:48
But it does accept empty values as in my example? Or do you have an example of where it doesn't work?

**Comment by droganov** [comment] 2015-02-12 11:54
No. it doesn't accept empty values. Here is my config:
https://github.com/droganov/Sdelkino.com-statics/blob/master/dev/blocks/form-classy/form-classy.coffee#L29

Rendered page is here: http://www.sd-statics.supremedesign.ru/publish.html

**Comment by ansman** [comment] 2015-02-12 13:38
Ah, the problem is that it doesn't accept empty strings. I'll make a fix for this.

**Comment by droganov** [comment] 2015-02-12 14:06
Great, thank you!

**Closed** 2015-03-04 19:51 UTC
